sudo: required
services:
  - docker

before_install:
  - docker build -t debiasej/multi-react-test-learning -f ./client/Dockerfile.dev ./client

script:
  - docker run debiasej/multi-react-test-learning npm test -- --coverage

after_success:
  - docker build -t debiasej/multi-client-learning ./client
  - docker build -t debiasej/multi-nginx-learning ./nginx
  - docker build -t debiasej/multi-server-learning ./server
  - docker build -t debiasej/multi-worker-learning ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push debiasej/multi-client-learning
  - docker push debiasej/multi-nginx-learning
  - docker push debiasej/multi-server-learning
  - docker push debiasej/multi-worker-learning

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-545284110187
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
